abbrevs:
  # GLOB
  - name: select files
    abbr-pattern: (?:~?/?(?:[.\w-]+/)*)(?:[.\w-]*)\*\*$
    snippet: |-
      $(
        abbr=${abbr%\*\*}
        fd --hidden --no-ignore --full-path --color always --exclude .git '' "${abbr:-.}" \
        | fzf --multi --height=50% --min-height=5 --info=inline
      )
    evaluate: true
    global: true

  # bat
  - name: bat --language=
    abbr: l
    snippet: --language=
    global: true
    context: '^bat\s'

  - name: bat --language=diff
    abbr: d
    snippet: --language=diff
    global: true
    context: '^bat\s'

  # cd
  - name: cd ..
    abbr: ..
    snippet: 'cd ..'

  - name: cd ../..
    abbr: ...
    snippet: 'cd ../..'

  - name: cd ../../..
    abbr: ....
    snippet: 'cd ../../..'

  - name: cd ../../../..
    abbr: .....
    snippet: 'cd ../../../..'

  - name: 'cd ~'
    abbr: '~'
    snippet: 'cd ~'

  # curl
  - name: curl method
    abbr: X
    snippet: |-
      -X $(cat <<EOT | fzf --height=6 --info=hidden --prompt='-X '
      GET
      POST
      PUT
      DELETE
      PATCH
      EOT
      )
    evaluate: true
    global: true
    context: '^curl\s'

  - name: curl header
    abbr: H
    snippet: |-
      -H $(cat <<EOT | fzf --height=2 --info=hidden --prompt='-H '
      'Content-Type: application/json'
      EOT
      )
    evaluate: true
    global: true
    context: '^curl\s'

  # ls
  - name: ls --long
    abbr: l
    snippet: 'exa --long'

  - name: ls --long --all
    abbr: ll
    snippet: 'exa --long --all'

  # ssh
  - name: ssh (silently)
    abbr: ssh-silent
    snippet: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR

  # find
  - name: find files
    abbr: FF
    snippet: find .{} -type f

  - name: find directories
    abbr: FD
    snippet: find .{} -type d

  - name: find (exclude .git node_modules vendor)
    abbr: FE
    snippet: find .{} -type d \( -name .git -o -name node_modules -o -name vendor \) -prune -o -print
